### ISSUE TITLE
dti_metrics error

### ISSUE THREAD

**Issue by mdesco** [scilus/freewater_flow#2]
Flow breaks on dti_metrics. Here is the error. Ran using scilpy master (not singularity)...

more work/9c/43822bf5e25a0c8d5bf43a469f3f62/.command.err
WARNING:root:Your b-vectors do not seem normalized...
/home/descotea/my_env/scilpy_public/lib/python3.7/site-packages/dipy/reconst/dti.py:498: RuntimeWarning: invalid value encountered in true_divide
  return 3 * np.sqrt(6) * determinant((A_squiggle / A_s_norm))
INFO:Compute_DTI_Metrics:Not enough b=0 images to output standard deviation map
/home/descotea/my_env/scilpy_public/lib/python3.7/site-packages/dipy/reconst/dti.py:1955: RuntimeWarning: divide by zero encountered in log
  D[..., 6] = -np.log(b0)
Traceback (most recent call last):
  File "/home/descotea/my_env/scilpy_public/bin/scil_compute_dti_metrics.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/descotea/scilpy/scripts/scil_compute_dti_metrics.py", line 457, in <module>
    main()
  File "/home/descotea/scilpy/scripts/scil_compute_dti_metrics.py", line 432, in main
    figsize=[10, 4.8])
  File "/home/descotea/my_env/scilpy_public/lib/python3.7/site-packages/matplotlib/pyplot.py", line 1184, in subplots
    fig = figure(**fig_kw)
  File "/home/descotea/my_env/scilpy_public/lib/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/home/descotea/my_env/scilpy_public/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/descotea/my_env/scilpy_public/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.7.4/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by GuillaumeTh** [comment]
That's not a scilpy issue. It is due to the cluster. You have no display on beluga so it crashed. You must to have the following line `backend : Agg` in your matplotlibrc. If you want the last scilpy in a singularity you can use the latest singularity from TractoFlow that I sent you.

**Comment by arnaudbore** [comment]
or latest scilpy container.
